<?php include 'head.php';?>
<?php include 'header.php';?>
<?php include 'content_index.html';?>
<?php include 'chargen/relationship_map.html';?>
<?php include 'chargen/attributes.html';?>
<?php include 'chargen/skills.html';?>
<?php include 'chargen/beliefs.html';?>
<?php include 'chargen/vampire.html';?>
<?php include 'chargen/background.html';?>
<?php include 'chargen/coterie.html';?>
<?php include 'footer.php';?>